//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.account_detail {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtwuzi;
		protected global::System.Web.UI.WebControls.TextBox txtdanwei;
		protected global::System.Web.UI.WebControls.TextBox txtdanjia;
		protected global::System.Web.UI.WebControls.TextBox txtshuliang;
		protected global::System.Web.UI.WebControls.TextBox txtaccount_id;
		protected global::System.Web.UI.WebControls.TextBox txtwuzi_id;
		protected global::System.Web.UI.WebControls.TextBox txtbeizhu;
		protected global::System.Web.UI.WebControls.TextBox txtbeizhu2;
		protected global::System.Web.UI.WebControls.TextBox txtbeizhu3;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
