//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.branch_company {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtpeixunban_id;
		protected global::System.Web.UI.WebControls.TextBox txtstart_detail;
		protected global::System.Web.UI.WebControls.TextBox txtend_detail;
		protected global::System.Web.UI.WebControls.TextBox txtnum;
		protected global::System.Web.UI.WebControls.TextBox txtnum_detail;
		protected global::System.Web.UI.WebControls.TextBox txtcleaning_fee;
		protected global::System.Web.UI.WebControls.TextBox txtfapiao_taitou;
		protected global::System.Web.UI.WebControls.TextBox txtbasketball_time;
		protected global::System.Web.UI.WebControls.TextBox txtfantang;
		protected global::System.Web.UI.WebControls.TextBox txtfangka_print;
		protected global::System.Web.UI.WebControls.TextBox txtyuedu_shuoming;
		protected global::System.Web.UI.WebControls.TextBox txtfengongsi;
		protected global::System.Web.UI.WebControls.TextBox txtdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
