//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.branch_company {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblpeixunban_id;
	protected global::System.Web.UI.WebControls.Label lblstart_detail;
	protected global::System.Web.UI.WebControls.Label lblend_detail;
	protected global::System.Web.UI.WebControls.Label lblnum;
	protected global::System.Web.UI.WebControls.Label lblnum_detail;
	protected global::System.Web.UI.WebControls.Label lblcleaning_fee;
	protected global::System.Web.UI.WebControls.Label lblfapiao_taitou;
	protected global::System.Web.UI.WebControls.Label lblbasketball_time;
	protected global::System.Web.UI.WebControls.Label lblfantang;
	protected global::System.Web.UI.WebControls.Label lblfangka_print;
	protected global::System.Web.UI.WebControls.Label lblyuedu_shuoming;
	protected global::System.Web.UI.WebControls.Label lblfengongsi;
	protected global::System.Web.UI.WebControls.Label lbldate;


       
    }
}
