//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.shangke_view {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtid;
		protected global::System.Web.UI.WebControls.TextBox txtkechengneirong_id;
		protected global::System.Web.UI.WebControls.TextBox txtpeixunban;
		protected global::System.Web.UI.WebControls.TextBox txtpeixunban_id;
		protected global::System.Web.UI.WebControls.TextBox txtkecheng;
		protected global::System.Web.UI.WebControls.TextBox txtjiangshi_id;
		protected global::System.Web.UI.WebControls.TextBox txtjiangshi;
		protected global::System.Web.UI.WebControls.TextBox txtkeshi;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
