//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.shangke_view {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblkechengneirong_id;
	protected global::System.Web.UI.WebControls.Label lblpeixunban;
	protected global::System.Web.UI.WebControls.Label lblpeixunban_id;
	protected global::System.Web.UI.WebControls.Label lblkecheng;
	protected global::System.Web.UI.WebControls.Label lbljiangshi_id;
	protected global::System.Web.UI.WebControls.Label lbljiangshi;
	protected global::System.Web.UI.WebControls.Label lblkeshi;


       
    }
}
