//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.hui_kuan_dan {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblhuikuan_neirong;
	protected global::System.Web.UI.WebControls.Label lblxiangmu_mingcheng;
	protected global::System.Web.UI.WebControls.Label lblxiangmu_zongkuan;
	protected global::System.Web.UI.WebControls.Label lblyifu_jine;
	protected global::System.Web.UI.WebControls.Label lblzhifu_shijian;
	protected global::System.Web.UI.WebControls.Label lblbenci_jine;
	protected global::System.Web.UI.WebControls.Label lblyuji_yukuan;
	protected global::System.Web.UI.WebControls.Label lblsupplier_id;
	protected global::System.Web.UI.WebControls.Label lblleibie;
	protected global::System.Web.UI.WebControls.Label lblbeizhu;


       
    }
}
