//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.wuzi_diaoyong {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblwuzi_id;
	protected global::System.Web.UI.WebControls.Label lblfengongsi;
	protected global::System.Web.UI.WebControls.Label lblnum;
	protected global::System.Web.UI.WebControls.Label lblpeixunbanid;
	protected global::System.Web.UI.WebControls.Label lblstyle;
	protected global::System.Web.UI.WebControls.Label lbltime;
	protected global::System.Web.UI.WebControls.Label lblbeizhu;
	protected global::System.Web.UI.WebControls.Label lblbeizhu2;


       
    }
}
