//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.supplier {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblperson;
	protected global::System.Web.UI.WebControls.Label lblphone;
	protected global::System.Web.UI.WebControls.Label lblphone2;
	protected global::System.Web.UI.WebControls.Label lblbank;
	protected global::System.Web.UI.WebControls.Label lblbank_num;
	protected global::System.Web.UI.WebControls.Label lbladdress;
	protected global::System.Web.UI.WebControls.Label lblstyle;
	protected global::System.Web.UI.WebControls.Label lblleibie;
	protected global::System.Web.UI.WebControls.Label lblwuzi;
	protected global::System.Web.UI.WebControls.Label lblbeizhu;
	protected global::System.Web.UI.WebControls.Label lblbeizhu2;


       
    }
}
