//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.dafen_jieguo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtshangke_id;
		protected global::System.Web.UI.WebControls.TextBox txtfenzu_id;
		protected global::System.Web.UI.WebControls.TextBox txtfenshu;
		protected global::System.Web.UI.WebControls.TextBox txtneirong;
		protected global::System.Web.UI.WebControls.TextBox txtdafen_xuhao;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
