//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.dafen_jieguo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblshangke_id;
	protected global::System.Web.UI.WebControls.Label lblfenzu_id;
	protected global::System.Web.UI.WebControls.Label lblfenshu;
	protected global::System.Web.UI.WebControls.Label lblneirong;
	protected global::System.Web.UI.WebControls.Label lbldafen_xuhao;


       
    }
}
